### PR TITLE
feat: update parser and add arrow function support

### PR DESCRIPTION
**Pull request by czosel**

### CODE REVIEW

**Comment by czosel** [comment]
@vjeux We recently switched to Github Actions, and still see AppVeyor builds in our PRs even though both the config file and the webhook were removed. Maybe it's triggered by a "organization webhook"? Would you have any way of shutting it down?

**Comment by czosel** [comment]
@loilo friendly ping :wink:

**Comment by vjeux** [comment]
@czosel yup, there seems to be an organization webhook for appveyor. Do you know who set it up by any chance? I have no idea how it works and don't want to break it :x

**Comment by czosel** [comment]
:sweat_drops: I suspect @ikatyang, see https://github.com/prettier/prettier/issues/7223

**Comment by vjeux** [comment]
@ikatyang can you delete the org wide appveyor setting since it seems to have been moved to actions?

**Comment by ikatyang** [comment]
Sorry for the late response, I've uninstalled the AppVeyor GitHub App for this org.

**Comment by czosel** [comment]
Thank you @ikatyang :100:

**Pull request merged**
