### PR TITLE
feat: improve output `class`, `extend`, `implement`declaration

### PR DESCRIPTION
**Pull request by evilebottnawi**
Based on prettier logic: [playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgMIbYBy6AtnDnAB7xQAmuACugE4IwFa4CWpADqjjlYuAJKw4LAGbowcTthzAAvgB0o6sIVwLMJcpRoIGOZm1i6cvAUPa4AapICejli+ev3bzz49-vzgAy0ADmAGLcgvpwAIxKahpQWlz42tGGtCZm7JbWgsIwDv5eJb4B5aXFZZUV1XXFwVDhkXDRcSrqmtqpXOnUmUW1VcMVjc1RZLFW-Pl2OOLw0rLy3R2JyYq6fUb0gzX79UNHByMnx2MRE+RxebYi8xJLcpZrXSlbkxnGe4dnf78A06-C4tNrTGwFH5A6FuEFXKavJLdD4GfrfHCA46Y-4wnGjUKXVqTG4zO6FDG47FUyk0-FNQlgxEbHRpT5o3amVg5bq3SEUrG0v5wonXAA01IFkqcwuiACZRfy8UrqjLJgBmeKdJHvVmonYmCVCgmg4ng2b3Q2WoLG+ExcWCq2wm0iuDyxWOpWq8gapnI3UUdkGh3BqUelXOsG8uZhwVe2L20Mhkpxt0xxNO+km72a9bdNPKpOGuNxQNMLkWHmkvkLSQyZ6rZQgUUgCB8GDcaCYZCgVgsCAAd2yUC7KHQADcINw6E2QFgYMgZKhMHBmwAjFiyADWcBgAGU+LJuE1kDAWABXFcgOgQMAL9BLy9H5csGCMDchUjoO8P5sAK0wVAAEIbmA257pMgRHnA37Ls2EBnjAfAIbKMGXgeLDPsgICrugq5OKg0AznwLBHjAADqU4wAAFsgAAcAAMzbERAy5kRufBYcRcDPmO0HNmwACOZ7cGwb7oB+X5IIusEgMupDcCe56XpgR4hIIACKZ4QPAqHNjAuEUXQ1HIPKICnugkSqXgECkJ+WFQNAfEgGey4ACq4SO0lwMoyhAA)

May incompatibility with https://github.com/php-fig/fig-standards/blob/6d44cdf2f06ab2440212facbaa3f3e787b24875d/proposed/extended-coding-style-guide.md#41-extends-and-implements.

/cc @korvinszanto @samdark @michaelcullum @rdeutz @danemacmillan @Jean85

Feel free to ping other people, if i somebody forget.

It would be good to hear your opinion on the compatibility with the PSR-12 :star: Because some advice in PSR-12 look ugly when you have very long `class` name or long extended `class` name.

### CODE REVIEW

**Comment by vjeux** [comment]
Those are pretty tricky. I'm not 100% happy with prettier output, especially when extensions have arguments/generics, but overall it does a decent job

**Comment by mgrip** [comment]
i definitely think its at least an improvement! Wouldn't be opposed to merging

**Comment by evilebottnawi** [comment]
@czosel @mgrip PSR-12 people unavailable :disappointed: We can merge this as is right now.

**Comment by MichaelDeBoey** [comment]
I think we should stick to the PSR-12 compatible case and put the `extends` and `implements` keywords on the same line.

In practice the extended class won't be that long I think?

**Comment by evilebottnawi** [comment]
@MichaelDeBoey Sometimes class name and extended class name very long, example look on symfony - a lot of classes very long and it is very hard to reading

**Comment by MichaelDeBoey** [comment]
@evilebottnawi Can you give me a link to an example?

**Comment by evilebottnawi** [comment]
@MichaelDeBoey 
```php

class UnexpectedValueException extends \UnexpectedValueException implements ExceptionInterface 
{
}
```

Longer 80 width, but we have issue around this https://github.com/prettier/plugin-php/issues/167, just vote, before first release we fix it :+1:

**Comment by MichaelDeBoey** [comment]
@evilebottnawi Already voted on #167 😉

**Pull request merged**
