### PR TITLE
feat: hardline after namespace

### PR DESCRIPTION
**Pull request by evilebottnawi**
:star:

### CODE REVIEW

**Comment by czosel** [comment]
Looking good, but tests are still failing..

**Comment by evilebottnawi** [comment]
@czosel already investigate

**Comment by evilebottnawi** [comment]
@czosel very strange locally all fine :confused: any idea?

**Comment by czosel** [comment]
Deleted the travis cache and restarted the build - just to exlude that potential source of trouble. I can take a closer look tomorrow morning otherwise.

**Comment by evilebottnawi** [comment]
@czosel my bug, after rebase all fine :+1:

**Pull request merged**
