### PR TITLE
release notes for 0.14.0

### PR DESCRIPTION
**Pull request by czosel**
Here are the release notes I drafted for 0.14.0 - this PR is not intended for merging, just for getting feedback. The actual release notes are directly in the "Releases" tab in GitHub :wink:

### CODE REVIEW

**Comment by czosel** [comment]
It's done! :tada: https://github.com/prettier/plugin-php/releases

Thanks @evilebottnawi and @loilo for the reviews.

**Comment by loilo** [comment]
> `5.3`, `5.2`, `5.1`, `5.0` and older

I don't think we should mention four versions and then say "and older". 😁 Maybe "`5.3` and below" would be the better wording here.

**Comment by czosel** [comment]
:+1: I'll change it directly in the release notes.

**Comment by loilo** [comment]
Playground is now running on 0.14 as well. 👌

**Pull request closed without merging**
