### PR TITLE
[WIP] tests: bom

### PR DESCRIPTION
**Pull request by evilebottnawi**
Should we remove BOM?

/cc @vjeux 

In PSR https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md#1-overview

Problem in prettier: https://github.com/prettier/prettier/issues/4050

### CODE REVIEW

**Comment by vjeux** [comment]
I would mirror what prettier js does in this case, we have special handling for BOM (but I didn’t write it so I’m not sure what we did exactly)

**Comment by evilebottnawi** [comment]
@vjeux prettier don't remove BOM, but PSR disallow using BOM, we can solve this inside our `parser.js`. Question: should we remove or not :confused:

**Comment by vjeux** [comment]
Then get rid of it. I don’t really care either way :)

**Comment by czosel** [comment]
I'll close this since it has become stale.

**Pull request closed without merging**
