### PR TITLE
chore: update parser to add numeric literal separator support

### PR DESCRIPTION
**Pull request by czosel**
Related to https://github.com/prettier/plugin-php/issues/854

### CODE REVIEW

**Comment by czosel** [comment]
We might want to wait until https://github.com/glayzzle/php-parser/pull/472/ has been merged.

**Comment by loilo** [comment]
Looks good to me. 👍 Agree on awaiting the merge though.

Out of curiosity: Do we intend to do any formatting related to numeric literal separators in the future? Has there been any thought on this?

**Comment by czosel** [comment]
I thought about it shortly, but I guess it's pretty difficult because of conflicting use-cases, e.g.:
```
# thousand separators
1_000_000
# currency
123_45
```

**Comment by czosel** [comment]
This has been merged in the parser, I'll merge this as well.

**Pull request merged**
