### PR TITLE
chore: updating parser to 3.0 pre-release

### PR DESCRIPTION
**Pull request by mgrip**
https://github.com/glayzzle/php-parser/releases/tag/3.0.0-alpha1

### CODE REVIEW

**Comment by mgrip** [comment]
thanks @ichiriac!

**Comment by evilebottnawi** [comment]
Just for track:
1. Need fix and tests https://github.com/glayzzle/php-parser/commit/1cf541bba7cf6bb279c398bcbc9480361f34b631
2. Break and Switch statements add tests https://github.com/glayzzle/php-parser/commit/f4f21cdd68eedd565aaf851d4ca8e3f45e0c002c

**Comment by mgrip** [comment]
I think those are both behind the `3.0.0-alpha1` release?

**Comment by evilebottnawi** [comment]
@mgrip no, https://github.com/glayzzle/php-parser/commits/master

**Comment by mgrip** [comment]
I'm confused - isn't the `3.0.0-alpha1` the most recent commit?

**Comment by evilebottnawi** [comment]
@mgrip yes, just before release `3.0.0-alpha1` we have two fixes, i wrote about these above

**Comment by evilebottnawi** [comment]
@mgrip feel free to merge :+1:

**Pull request merged**
