### PR TITLE
tests: cast

### PR DESCRIPTION
**Pull request by evilebottnawi**
Parser problem:
https://github.com/glayzzle/php-parser/issues/119

In future we can discussion about `int` vs `integer` and etc.

### CODE REVIEW

**Comment by czosel** [comment]
In the past we agreed to always use short forms, since PSR-12 seems to go that way - see https://github.com/prettier/plugin-php/pull/5#discussion_r158664155
That would also mean that we don't need any change in the parser. What do you think?

**Comment by evilebottnawi** [comment]
@czosel we can't change logic in our code (we use short forms), but parser should be return all data, it is related to parser. What about `(float)` vs `(double)` vs `(real)`

**Comment by czosel** [comment]
@evilebottnawi i meant just the short forms: Here i think we should always print `(int)`, also if it was `(integer)`.

**Comment by evilebottnawi** [comment]
@czosel right now we print always `int`, but `float` when you use `double` or `real`, should we fix this in parser?

**Comment by czosel** [comment]
Actually i think the argument in https://github.com/prettier/plugin-php/pull/5#discussion_r158664155 means that we should always print `float`, because the aliases `double` and `real` are not supported for type hinting. I'd say it makes sense to have one consistent form for casts and type hints.

**Comment by evilebottnawi** [comment]
@czosel agree :+1:

**Pull request merged**
