### PR TITLE
Fix wrong heredoc indentation in calls

### PR DESCRIPTION
**Pull request by bug-tape**
Should fix https://github.com/prettier/plugin-php/issues/1624

### CODE REVIEW

**Comment by czosel** [comment]
Looks like the tests are failing, can you try updating the snapshots?

**Comment by bug-tape** [comment]
Would it be possible to make a release with the fix?

**Comment by czosel** [comment]
Of course! Just released this as `v0.16.3`. Sorry for the delay.

**Comment by bug-tape** [comment]
Yeah! Back in business.
Thanks!

**Pull request merged**
