### PR TITLE
Remove mgrip from active maintainers

### PR DESCRIPTION
**Pull request by mgrip**
As you guys probably figured out by now I've been working on other things and don't have much time to devote to this anymore 😢 I left my job where I was actively using php (as far as I know they're still using this plugin though!)

I'm happy to answer questions and help out where I can but I just don't have a ton of time to devote to this, so thought I could remove myself from the list of active maintainers. I'm still super excited to see this get to a 1.0 and become the gold standard for php formatting! ⭐️ Keep up the great work @evilebottnawi and @czosel! I'll be watching from the sideline 😄

### CODE REVIEW

**Comment by mgrip** [comment]
😞

**Comment by czosel** [comment]
@mgrip While it's sad to loose you as a contributor, it's also totally understandable that you're focussing on other things - especially if you're not actively using PHP anymore. I think it's a good moment to thank you for getting this started in the first place, and for your many contributions! :1st_place_medal: 

I'd also like to devote more time to this (these days I'm mostly just reviewing @evilebottnawi's work), but regular work often has higher priority. Still I'm excited to help as much as possible and for us to reach 1.0 in the future :star2: 

@evilebottnawi by the way, I'll be on holiday for the coming 3 weeks, and I decided to leave my laptop at home. Don't worry, I'll be back after, even if it's just for some reviews :wink:

**Comment by evilebottnawi** [comment]
@czosel don't worry, no new options :smile: only ugly fixes and bug fixes

**Comment by czosel** [comment]
now I can leave without worries :sweat_smile:

**Pull request merged**
