### PR TITLE
fix: insert pragma when first docblock mid-file (#1310)

### PR DESCRIPTION
**Pull request by leighman**
Thought I'd give it a try. No idea if this is sane.

### CODE REVIEW

**Comment by leighman** [comment]
@czosel since you seem to be around and this is blocking us using the plugin. Sorry if you're not right to review this.

**Comment by czosel** [comment]
Unfortunately we can't cut a release from the current `master` branch yet because some changes still have to land related to #1280. Let me know you'd like a `0.12.1` release with this feature cherry-picked from the last release.

**Comment by leighman** [comment]
Thanks. Definitely wouldn't say no to a `0.12.1` ;)

**Comment by czosel** [comment]
Just released this as part of `0.13.0` :slightly_smiling_face:

**Pull request merged**
