### PR TITLE
Support expressions in new statement

### LINKED ISSUE #2082: prettier cannot deal with class instantiation from a config
Prettier cannot format the following code:

```php
        $client = new (config('wd.authentication.models.client')(['name' => $data['name']]));
```
I am getting:

```php
[error] src/Http/Controllers/RegisterController.php: SyntaxError: Parse Error : syntax error, unexpected '(' on line 48
[error]   46 |     protected function create(array $data): BaseUser
[error]   47 |     {
[error] > 48 |         $client = new (config('wd.authentication.models.client')(['name' => $data['name']]));
[error]      |                      ^
[error]   49 |         $client->save();
[error]   50 |
[error]   51 |         $user = $this->getUserObject()::create($this->getNewUserData($data));
```

WorkAround:

```php
        $ClientModel = config('wd.authentication.models.client');
        $client = new $ClientModel(['name' => $data['name']]);
```

### PR DESCRIPTION
**Pull request by cseufert**
Requires upstream fix in PHP-Parser
https://github.com/glayzzle/php-parser/pull/1020

closes #2082

### CODE REVIEW

**Comment by czosel** [comment]
Hi @cseufert, sorry about the delay. I just released `v3.1.2` of the parser containing the fix :tada:

**Comment by cseufert** [comment]
@czosel I have updated this PR with the 3.1.2 version of the parser

**Review by czosel — APPROVED** [review]
:+1:

**Comment by czosel** [comment]
Released in `v0.19.2` :tada:

**Pull request merged**
