### PR TITLE
fix(match): Support empty lines and comments in match expressions (closes #1956)

### LINKED ISSUE #1956: Comments in match statement throw error
**@prettier/plugin-php v0.18.3**
[Playground link](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBZhqYAGpIlWfCDoA6AIwgWMCG3iyVAYXQBbH2wAFAAkA-BdBQxAOVwBjKABlGABPNWswbAgAWgAmJxBoAEdBeGgA12V-PTkFEGIRCBgytgq2KoMAXxYoCngYdBQ0eCxJUDZsGDaRTtrMMEEJvBAAHgB+YzAAHUwtqUFMGIxMAAIpeAAvM45BC4AKYhgjgBJ4AEot4C2jr6OiEiP-GAxahHG4MF5HD7Hb7QgD0ACojjR4NgjsijmwjjFfD4oH84TDPtDvs8jgBSI72ACsRwAvAA+I4bECnC5XC5MpiEolPeBko4AZlpDKZLLOHK5RJJ5Op9MZUWuYqcEuhFCgMkEsgesuenKhX3aR1sR2CAQA+gBRZAAGQA3Ft2iB2kA)

**Input:**
```php
<?php

function fizzbuzz(int $i)
{
    print match (0) {
        /* this is a comment */
        $i % 15 => "fizzbuzz",
        $i % 3 => "fizz",
        $i % 5 => "buzz",
        default => $i,
    } . PHP_EOL;
}
```

**Output:**
```php
Comment "/* this is a comment */" was not printed. Please report this error!
```

Of note, it doesn't matter what kind of comment, or where the comment is (end of line, before/after a pattern, etc.). Every scenario throws an exception.

### PR DESCRIPTION
**Pull request by claytonrcarter**
**What does this do**
- preserves empty lines between match arms
- collapses multiple empty lines between match arms into one empty line
- prints leading comments between match arms (#1956)
- prints trailing comments after match arms
    - this honors `trailingCommaPHP` option, though the tests for comments don't use that option, so there's no test coverage for it
- adds tests for new and changed behavior
- all changes have been formatted 😉  

**Current behavior on `main`**
- all empty lines between arms are discarded
- leading and trailing comments trigger error: "Error: Comment "`<comment>`" was not printed. Please report this error!" 

Hi, I've been using `prettier/plugin-php` for years, but this is my first contribution. I have no idea if I have completed all PR requirements, nor if my solution is following all of the idioms,, so please let me know and I'll glady update this.

This was a pretty easy to change once I learned how the parser and printer everything fit together. The upstream parser was already including comments in the AST for `match`, but the printer was not making use of them. I tried to support empty lines and comments as they are handled for function params, and I was mostly successful. The only part that I couldn't get is comments that are followed by an empty line:
- in function args, if there is an empty line between the comment and the arg, it is preserved
- in this PR, empty lines between a comment and the next match arm are discarded
- I'm not sure how important this is, though, and welcome your input!

Thank you!

## Example 1: no comments
**Input**
```php
match($v) {

    'a' => 1,


    'b' => 2,

    default => null
};
```
**Output**
```php
match ($v) {
    "a" => 1,

    "b" => 2,

    default => null,
};
```
**Current behavior on `main`**
```php

match ($v) {
    "a" => 1,
    "b" => 2,
    default => null,
};
```

## Example 2: with comments
**Input**
```php
match($v) {

    // first comment

    'a' => 1,


    /*
     * second comment
     */

    'b' => 2,
    default => null            // final comment
};
```
**Output**
```php
match ($v) {
    // first comment
    "a" => 1,

    /*
     * second comment
     */
    "b" => 2,
    default => null, // final comment
};
```
**Current behavior on `main`**
```
Error: Comment "// first comment" was not printed. Please report this error!
```

### CODE REVIEW

**Comment by claytonrcarter** [comment]
Sorry for the false start. I just fixed the `let`/`const`.

**Comment by czosel** [comment]
No worries at all! I’ll try to take a closer look at this soon.

**Review by czosel — APPROVED** [review]
This looks great! Thank you for this excellent contribution :100:

**Comment by czosel** [comment]
Released in `v0.19.7` :tada:

**Pull request merged**
