### PR TITLE
Attempt to fix the formatting of long cases in match statement

### PR DESCRIPTION
**Pull request by czosel**

### CODE REVIEW

**Comment by czosel** [comment]
Forgot to push my commit :see_no_evil: should be ready for review now.

**Comment by czosel** [comment]
@cseufert friendly ping :)

**Review by cseufert — APPROVED** [review]
Thanks, looks good. Prettier is a bit of black magic sometimes.

**Comment by czosel** [comment]
Yeah :sweat_smile: Thanks for the review!

**Comment by czosel** [comment]
Released in `v0.19.0` :tada:

**Pull request merged**
