### PR TITLE
feat: add support for named arguments and nullsafepropertylookup (php8)

### LINKED ISSUE #1599: PHP 8 support?
Does it support PHP 8?

thanks

### PR DESCRIPTION
**Pull request by czosel**
Fixes #1599 

cc @Selion05

Ready in this PR:

- [x] nullsafepropertylookup
- [x] named arguments

Landed in parser:

- [x] match expression: https://github.com/glayzzle/php-parser/pull/686
- [x] union types: https://github.com/glayzzle/php-parser/pull/692, https://github.com/glayzzle/php-parser/pull/693

Open:

- [ ] promoted properties: https://github.com/glayzzle/php-parser/pull/697

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]

**Comment by czosel** [comment]
Thanks for taking a look @alexander-akait! I'd say we leave this open a little longer, at least until the named arguments support has landed in the parser's `php8` branch.

**Comment by czosel** [comment]
@cseufert If you'd like to implement some of the new features that you implemented in the parser, feel free to add commits to this PR :slightly_smiling_face: I usually link to a specific commit SHA in the parser's `php8` branch, because linking to the branch itself confuses the CI caches.

**Comment by milewski** [comment]
https://github.com/glayzzle/php-parser/pull/697 has been merged... are we all good now?

**Comment by cseufert** [comment]
> @cseufert If you'd like to implement some of the new features that you implemented in the parser, feel free to add commits to this PR  I usually link to a specific commit SHA in the parser's `php8` branch, because linking to the branch itself confuses the CI caches.

@czosel I have implemented the other features in a seperate PR #1744 

@milewski This should mean everything apart from Attributes from PHP8 should be now be supported when both of these PR's get merged.

**Comment by czosel** [comment]
@cseufert Alright, let's go ahead and move this one and #1744 forward :rocket:

**Pull request merged**
