### PR TITLE
feat: enable GitHub actions

### PR DESCRIPTION
**Pull request by czosel**
- [ ] Windows build
- [ ] Coverage upload
- [x] Remove appveyor and travis

### CODE REVIEW

**Comment by czosel** [comment]
The windows build is failing due to LF/CRLF issues - interesting that appveyor didn't catch this...

**Comment by czosel** [comment]
Uploading to codecov currently doesn't seem to work from forks:
https://github.com/codecov/codecov-action/issues/29
https://github.com/codecov/codecov-node/issues/118

Maybe we should skip it for now?

**Comment by loilo** [comment]
Sorry, I'm **so** not qualified to review this. 🙈

**Comment by czosel** [comment]
😅 How come?

**Comment by loilo** [comment]
I have not even remotely had any contact with GitHub actions. 😅

**Comment by czosel** [comment]
Me neither until a few hours ago :sweat_smile:

**Comment by czosel** [comment]
I'd love to see if the build over at #1269 would work with GitHub actions. I guess I'm gonna go ahead and merge this - we can always revert it if someone has an issue with it :see_no_evil: 

cc @evilebottnawi

**Comment by czosel** [comment]
The build of #1269 really works with GitHub actions. Let's go ahead and replace the travis caching issue with a new, hopefully small set of future issues with GitHub actions :wink:

**Comment by evilebottnawi** [comment]
All good

**Pull request merged**
