### PR TITLE
fix: don't duplicate php8 attributes

### LINKED ISSUE #1820: php8 attributes clones last attribute on methods
**Prettier 2.1.2**

**PHP Plugin 0.17.4**

**Input:**

```php
<?php

declare(strict_types=1);

namespace App\Shared\Domain\Event;

final class DomainEventMessage
{
    #[Some(type: "some_type")]
    public function getPayload(): string
    {
        return "444";
    }

    public function getPayload1(): string
    {
        return "555";
    }

    public function getPayload2(): string
    {
        return "666";
    }
}

```

**Output:**

```php
<?php

declare(strict_types=1);

namespace App\Shared\Domain\Event;

final class DomainEventMessage
{
    #[Some(type: "some_type")]
    public function getPayload(): string
    {
        return "444";
    }

    #[Some(type: "some_type")]
    public function getPayload1(): string
    {
        return "555";
    }

    #[Some(type: "some_type")]
    public function getPayload2(): string
    {
        return "666";
    }
}
```

**Expected behavior:**
output just one method should have attributes.

### PR DESCRIPTION
**Pull request by czosel**
fixes #1820

### CODE REVIEW

**Comment by czosel** [comment]
not sure why CI is failing ...

**Comment by alexander-akait** [comment]
bug in node.js

**Review by fernando-rivas-smtp — APPROVED** [review]

**Comment by fernando-rivas-smtp** [comment]
maybe re running the ci?

**Comment by czosel** [comment]
@fernando-rivas-smtp doesn't seem to help …

**Comment by alexander-akait** [comment]
@czosel Very weird, let's try to update deps

**Comment by alexander-akait** [comment]
@czosel Bug report https://bugs.chromium.org/p/v8/issues/detail?id=12188

**Comment by alexander-akait** [comment]
Bug even in V8

**Comment by czosel** [comment]
@alexander-akait wow, interesting! Shall we merge anyway for now, since "only" our test suite seems to be affected?

**Comment by alexander-akait** [comment]
@czosel I think we can merge it

**Pull request merged**
