### PR TITLE
fix: multi-line conditions

### PR DESCRIPTION
**Pull request by mgrip**
https://github.com/prettier/plugin-php/issues/139

### CODE REVIEW

**Comment by czosel** [comment]
This looks awesome! I have two comments:

* Is the JS printer doing the same thing?
* Should we try to add some more tests for all the cases where `shouldFlatten` returns false?

**Comment by evilebottnawi** [comment]
Tests always welcome :+1:

**Comment by mgrip** [comment]
Yup! I stole the general idea from the JS printer - https://github.com/prettier/prettier/blob/master/src/language-js/printer-estree.js#L4706. I'll add some more tests - feel free to add more after this gets merged too! I'm guessing this won't cover edge case but I think its a good starting point that we can start to open up more specific issues

**Comment by mgrip** [comment]
new test cases are a little strange but thats how [JS prints them](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBQBIYAWqAzpgD5mb4ECGMmAZA1YXAPKsBOAKkVAOaYAPFWIQAtnABKcGgBs5ATxnylKhYoAy0fgCEIEObKgA1Gp1Q0ARkYCUmYAB0omTJzgwArpxcxOnuABuZwBfZ2cMHGoSckpqOkZmanYuXlQBYVEJaVkNdTVcpW0BfUNjMwtrI0wAXhqqOABHT3kAYQI4MABreycXNw9vX38g0JAAGhAIAAcYVGhiZFBzTggAdwAFcwRFlBoANwhUABMJkBpiGGR0eWI4SatOGm6PAGVp5-T+ZD8AyeOIGBrrd7mgoHdODANk9+OIaMC5HdJgArYgAD10TxeMFeNEkmnScARSKmnhg0zJACZiaCPpwIcgQFZrIo5NAztMLLAAOonQjIAAcAAZJpyIHduU9pozOXAIfsiZN3M1UO5oTRYfCkDdEaC7uJUD8RpNiF8jABFTwQeA0yYway8478pCUu1PVByL6tCRwxlQaCKkCeO7cay7HV3EIhIA)

**Comment by evilebottnawi** [comment]
@mgrip let's add tests around `(` and `)`. Example:
```php
if (($this || $that) && $theOtherThing < $someReallyReallyReallyLongBooleanVariable == $equalCheck) {
  return true;
}
```

And we can merge :+1:

**Comment by mgrip** [comment]
confirmed [same as JS](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBTYCQwAWqAzpgD7mYGECGMAlJgGTPVFwDyHATgCrEoAc0wAeaiQgBbOACU4tADaKAnvKWr1ylQBloQgEIQIihVABqtHqloAjU5gC8j6nACOAVyUBhQnDAA1kzAADpQmJg8cDAePOEwPB5wANxhAL4gADQgEAAOMKjQJMigVjwQAO4AClYIxSi0AG4QqAAmWSC0JDDI6EokcNm2PLSB0QDKuaOowsgJSdmtEGC9-YNoUAM8MFUjQlK0q4oD2QBWJAAeBiNjMOO0MjozcEcnOR4wuR8ATK-rUzwtsgQLY7CpFNAOrlrLAAOptIjIAAcAAZstCIANYSNcsDoXAto0Xtkop5UFFdrR9ockH1jusBlJUHNEgyZkJTABFDwQeB-bIwOzw1qIpDfAUjVCKdneaQHYFQaDEkAeAZ8Oz1OkDNJpIA) 👍

**Comment by czosel** [comment]
:100:

**Comment by upwebdesign** [comment]
This is not valid PSR-2 according to `phpcs`. 

```php
if (
    $e instanceof NotFoundHttpException ||
    $e instanceof ModelNotFoundException ||
    $e instanceof RelationNotFoundException
) {
    return response()->json(['message' => 'Resource not found :: ' . $e->getMessage()], 404);
}
```

It should be:

```php
if ($e instanceof NotFoundHttpException ||
    $e instanceof ModelNotFoundException ||
    $e instanceof RelationNotFoundException
) {
    return response()->json(['message' => 'Resource not found :: ' . $e->getMessage()], 404);
}
```

Thoughts?

**Comment by nicoder** [comment]
see section 5.1 of [PSR-12](https://www.php-fig.org/psr/psr-12/) :

> Expressions in parentheses MAY be split across multiple lines, where each subsequent line is indented at least once. When doing so, the first condition MUST be on the next line.

**Comment by upwebdesign** [comment]
@nicoder thanks for the clarification. I was under the assumption that PSR-2 was being used. I updated PHPCS and will see how it goes.

**Pull request merged**
