### PR TITLE
fix: update parser to remove extra linebreak in nowdoc

### PR DESCRIPTION
**Pull request by czosel**

### CODE REVIEW

**Comment by czosel** [comment]
Shall we start preparing a release? 🙃

**Comment by loilo** [comment]
Shall we? May be worth to address #939 first as it's the last missing feature touched by the `phpVersion` option... (Probably? Not sure about #493.) Would be nice to release them all together.

**Comment by czosel** [comment]
Right - i totally forgot about #939 because it's so easy to implement :sweat_smile: #493 is already implemented though.

**Comment by czosel** [comment]
Done: #1289 :wink:

**Pull request merged**
