### PR TITLE
Creating option for moving opening declaration brace to new line

### PR DESCRIPTION
**Pull request by mgrip**
#107 #54

### CODE REVIEW

**Comment by mgrip** [comment]
So I mostly solved for #54 with this PR - one thing we still need to address though is _not_ breaking between `) {` if the function breaks. ie

```php
function reallyLongFunctionName(
  $argument,
  $argument2
)
{
```
should actually be
```php
function reallyLongFunctionName(
  $argument,
  $argument2
) {
```

It seems like thats gonna be complicated though so once this gets merged I'll open a new issue for it

**Comment by mgrip** [comment]
🎉

**Comment by evilebottnawi** [comment]
/cc @vjeux 

we need remove new option

**Comment by evilebottnawi** [comment]
@mgrip @czosel don't do this, it is bad, very bad

**Comment by mgrip** [comment]
why?

**Comment by evilebottnawi** [comment]
@mgrip no option, it is prettier, please read https://prettier.io/docs/en/option-philosophy.html

**Comment by mgrip** [comment]
In my mind this is similar to

> --jsx-bracket-same-line was needed for a big company with a huge code base (Facebook), which backed the project when it got started, to be able to adopt Prettier at all.

I did post an issue on this first and the only feedback on it was 2 👍 . I think my argument from the original issue posting still stands, but happy to continue that discussion if you'd l like

**Comment by evilebottnawi** [comment]
@mgrip let's revert option and open issue with vote

**Comment by mgrip** [comment]
I'd rather not revert it - the actual option is 1 loc. If we really think we should remove it I will remove that loc but I'd like some other opinions first

**Comment by czosel** [comment]
I think this example from prettier for JS fits even better with our situation:
> --arrow-parens was added after huge demand. Prettier has to strike a balance between ideal goals and listening to the community.

**Comment by evilebottnawi** [comment]
@mgrip @czosel we should have discussion about option, no merge without issue and vote. Each option increase complex and add new problem in future

**Comment by mgrip** [comment]
There was an issue, I got no opposition to it before it was merged - I just reopened it if you want to continue the discussion there #107

**Comment by evilebottnawi** [comment]
@mgrip we merge this without my vote :trollface:

**Comment by mgrip** [comment]
Tbh I didn't think this would be controversial - for reasons stated above and in the issue

**Comment by evilebottnawi** [comment]
@mgrip @czosel  I'm not against the option or not specifically this option, the only problem is that adding one option other will want more options, and each will complicate the maintenance of the project and deliver only problems, our goal is to make the code beautiful, not optional, for this we have linter
In js `prettier + easlint`
In css `prettier + stylelint`
In php `prettier + PHP_CodeSniffer`

**Comment by mgrip** [comment]
I definitely agree - it just seems like this is probably the largest difference between formatting standards across php code. Like I mentioned originally I'm worried not having this option will prevent people from using prettier for php

**Comment by mgrip** [comment]
Also lets keep discussion on the open issue pls 😄 https://github.com/prettier/plugin-php/issues/107

**Comment by evilebottnawi** [comment]
@mgrip we need revert :smile:

**Comment by nonoroazoro** [comment]
This is why I'll never use prettier.

**Pull request merged**
