### PR TITLE
test: HTML line endings

### PR DESCRIPTION
**Pull request by Myhlamaeus**
* Make changes in CR characters visible (4c38a0e)
* Add tests for CRLF in HTML (related to #665) (660cbae)

### CODE REVIEW

**Comment by Myhlamaeus** [comment]
I would have to remove the part which prints the line endings, then, meaning that changes concerning them would not be visible (or I would have to manually edit all the tests, which seems obnoxious). I don’t know why the previous snapshots are actually correct on Travis, though, as they certainly aren’t for me locally.

**Comment by evilebottnawi** [comment]
@Myhlamaeus because in prettier test we format tests as before, don't change all tests, only what show and fix problem.

**Comment by evilebottnawi** [comment]
@Myhlamaeus Thanks for example and test, WIP on this

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/prettier/plugin-php/pull/712

**Pull request closed without merging**
