### PR TITLE
feat: add support for typed properties (PHP7.4)

### LINKED ISSUE #854: Support php7.3 and php7.4
No issue template. We need improve parser (https://github.com/glayzzle/php-parser):

# php7.3

- [x] Support trailing commas in `call`/`isset`/`unset` (spec https://wiki.php.net/rfc/trailing-comma-function-calls)
- [ ] Support new syntax for NowDoc and HereDoc (spec https://wiki.php.net/rfc/flexible_heredoc_nowdoc_syntaxes)
- [x] Array Destructuring supports Reference Assignments
- [x] Instanceof Operator accepts Literals (i think we already support, need add tests)

# php7.4

- [x] https://wiki.php.net/rfc/null_coalesce_equal_operator
- [x] https://wiki.php.net/rfc/typed_properties_v2
- [x] https://wiki.php.net/rfc/arrow_functions_v2
- [x] https://wiki.php.net/rfc/spread_operator_for_array
- [x] https://wiki.php.net/rfc/numeric_literal_separator

Something missing? Any help welcome :+1:

### LINKED ISSUE #1336: [Bug] Object property types are being deleted
Looks like class property types are just being removed since updating to the latest version of prettier-php.

**Input**
```
protected Organization $organization;
protected string $event;
protected string $jobId;
protected string $candidateId;
```

**Output**
```
protected $organization;
protected $event;
protected $jobId;
protected $candidateId;
```

**Versions:**
prettier: 1.19.1
@prettier/plugin-php: 0.13.0

### PR DESCRIPTION
**Pull request by czosel**
Fixes #1336

Together with the other open PRs, this completes #854 :tada:

### CODE REVIEW

**Comment by mauriau** [comment]
Nice !  
I need it :)

**Comment by loilo** [comment]
A little FYI here: I'll have to cut back on my open source work for a couple weeks until the whole COVID-19 situation normalizes a bit, since I'll now have to manage my job and a kid at the same time, which will probably be a little bit challenging. 😁

Just to say that no reaction from me on a review request does not imply any disapproval of the PR. 😉

**Comment by evilebottnawi** [comment]
Health is more important

**Comment by loilo** [comment]
No doubt. We're all fine in the family, but not having child care will reduce my spare time to a minimum. 😄

I'll be back. 🕶

**Comment by czosel** [comment]
@loilo no worries - take care and stay safe!

for me it's kind of the other way around, most free time activities that kept me from open source work are forbidden now :sweat_smile:

**Pull request merged**
