### PR TITLE
Update tabWidth to 2

### PR DESCRIPTION
**Pull request by marcofugaro**
From the README

However, when clicking the link, https://prettier.io/docs/en/options.html#tab-width

This PR sets the default `tabWidth` to `2`

### CODE REVIEW

**Comment by evilebottnawi** [comment]
We use `4` for php because it is recommendation from PSR

**Comment by czosel** [comment]
With "Same as in Prettier" is meant that the option has the same meaning as in Prettier for JS - not that should also have the same default value :wink:

Probably we could try to be a bit clearer about this in the README.

**Comment by marcofugaro** [comment]
Oh ok, my bad. Yes, it needs to be specified in the README instead of "Same in prettier"

**Comment by evilebottnawi** [comment]
@marcofugaro Feel free to open an issue about it

**Pull request closed without merging**
