### PR TITLE
feat: flexible heredoc support

### PR DESCRIPTION
**Pull request by czosel**

### CODE REVIEW

**Review by evilebottnawi — COMMENTED** [review]
Looks good, but let's add more tests for php less 7.3

**Comment by czosel** [comment]
Actually all the changed tests are running for PHP < 7.3 as well. They didn't change, so no diff there :upside_down_face:

**Comment by evilebottnawi** [comment]
Sounds good

**Comment by czosel** [comment]
:+1: Thanks for the quick review!

**Pull request merged**
