### PR TITLE
chore: update prettier to 2.1.1

### PR DESCRIPTION
**Pull request by czosel**

### CODE REVIEW

**Comment by czosel** [comment]
Prettier 2.1.1 seems to cause a minor change in the way we're formatting inline nodes at the end of a file. What do you think @evilebottnawi - safe to merge or do we need to investigate?

**Review by evilebottnawi — COMMENTED** [review]
Yes, we should solve it, it is regressions :disappointed:

**Comment by cseufert** [comment]
I feel like it the opening `<?php` tag should be on its own line as well if we are going to leave the closing tag on its own line.

**Comment by czosel** [comment]
closing in favor of #1774

**Pull request closed without merging**
